### ISSUE TITLE
Feature request: Make ackImmediate() return a Promise

### ISSUE THREAD

**Issue by dko-slapdash** [kagis/pgwire#11]
It would be a simple change:

```js
  ackImmediate(lsn) {
    this.ack(lsn);
    this._ackTimer.refresh();
    return new Promise(resolve => {
      if (this._tx.writableHighWaterMark > this._tx.writableLength) {
        this._tx.write(updateStatusMessage(incLsn(this._ackingLsn)), resolve);
      } else {
        resolve(false);
      }
    });
  }
```

**Comment by exe-dealer** [comment]
Can you please describe the case where you need to wait for flush of ack message?
I check node docs and found that write callback may be called with no error object when error occures. And flush event on stream does not garanties that ack message was handled by postgres.
I noticed that postgres sends some keep-alive message just after client keep-alive (ack) message. This backend message may be a response to ack message, which we can use to resolve promise, but Im not shure because pg documentation says nothing about it

**Comment by exe-dealer** [comment]
and if you need this feature because of backpreassure then why not just use .ack() instead of .ackImmediate() ?

**Comment by dko-slapdash** [comment]
Yeah, you’re right. I thought it’s an easy thing to implement, just at the level of streams, but in practice it’s much more complicated. And I didn’t have a strong needs for this feature actually.

So we may close this.

**Comment by jmealo** [comment]
@exe-dealer: can we close this?

**Comment by exe-dealer** [comment]
@jmealo yes

And I don't want to support this lib, because node streams looks buggy, overcomplicated and dissapointing. I'm working on porting this lib to deno now and want to migrate our company projects to deno
