### ISSUE TITLE
ssl support

### ISSUE THREAD

**Issue by exe-dealer** [kagis/pgwire#8]

**Comment by dko-slapdash** [comment]
JFYI, until SSL is supported in the library, here's a work-around:

```
$ cat /etc/stunnel/postgres.conf
[postgres]
client=yes
protocol=pgsql
options=NO_TICKET
accept=127.0.0.1:5432
connect=my-postgres-server:5432

$ psql -h 127.0.0.1 "sslmode=disable"
> create extension sslinfo;
CREATE EXTENSION
> select ssl_is_used();
 ssl_is_used
-------------
 t
```

**Comment by dko-slapdash** [comment]
Actually, after some thinking, I would strongly advocate for this feature. Because with stunnel, it makes the configuration much more complicated (we have an environment variable with the list of all master postgres machines, and with stunnel, we would’ve need to keep its config file in sync with the environment variable which is ugly).

FYI: currently for non-streaming purposes we use https://node-postgres.com/features/ssl library. Enabling ssl there is as simple as passing `ssl: true` to Client’s constructor (and then it does the “default” things, so we don’t even need to pass the paths to client certificates). We run on AWS RDS.

**Comment by exe-dealer** [comment]
implemented
