### ISSUE TITLE
How to close replication?

### ISSUE THREAD

**Issue by ArturFormella** [kagis/pgwire#9]
Hello!
I would like to close connection gracefully on some event. How to do that?

```
const events = replstream.pgoutput();
for await (const pgomsg of events) {
  const saveSuccess = await sendToHana(hanaClient, pgomsg);
  if (saveSuccess) {
    replstream.ack(pgomsg.lsn);
  }
}
event.then( () => {
   // ???
})

```

**Comment by exe-dealer** [comment]
just call `replstream.end()` 

```js
if (saveSuccess) {
    replstream.ack(pgomsg.lsn);
    replstream.end();
}
```

**Comment by exe-dealer** [comment]
to close connection you should also call `connection.end()` after `replstream.end()`

**Comment by exe-dealer** [comment]
I just realized that `replstream.end()` is useless because it makes possible to receive some buffered messages after `replstream.end()` call. But receiving this mesagges makes no sence because we cannot ack them after `.end()` anyway. Attempt to .ack message after .end will cause exception. Replication client should call `replstream.destroy()` instead of `replstream.end()` (or do `break` in async loop) to stop replication in proper way.

So I'm going to remove `replstream.end()` function
